# This workflow will publish any new release to the npmjs registry

name: Publish
permissions:
  id-token: write
  contents: read

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - run: npm run lint:ci
      - run: npm publish --access public
